language:
  - python

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - pep8 --ignore=E501 numerov.py
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then py.test -vv -s numerov.py --cov numerov;
    else py.test -vv -s numerov.py;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then coveralls;
    fi

notifications:
  email: false
